exports.voiceList = [
    'Drake',
    'Kanye West (rapping)',
    'Snoop Dogg',
    'ZWF',
    'Walter White',
    'Moistcr1tikal',
    'Peter Griffin (current)',
    'Eminem (pronunciation dict)',
    'Rick Sanchez',
    'Mario',
    'Chills',
    'Heavy',
    'Scout',
    'Morgan Freeman',
    'Arthur Morgan',
    '2Pac',
    'Eminem (all eras)',
    'Juice WRLD (Rapping)',
    '21 Savage',
    'Sonic (Jason Griffith, Games)',
    'The Narrator (Ultra Deluxe)',
    'Kanye West (Ye)',
    'Juice WRLD (Singing)',
    'Baldi',
    'Twilight Sparkle',
    'Eminem (Freestyle)',
    'GLaDOS (Portal 2) (Crust)',
    'Spy',
    'Sonic (Roger Craig Smith)',
    'Patrick Star'
]